.PHONY: all
all:
	make numpy-1.16.1-cp36-cp36m-linux_aarch64.whl
	make scikit-image-0.14.2-cp36-cp36m-linux_aarch64.whl

numpy-1.16.1-cp36-cp36m-linux_aarch64.whl:
	pip3 wheel numpy==1.16.1
scikit-image-0.14.2-cp36-cp36m-linux_aarch64.whl:
	pip3 wheel scikit-image==0.14.2
