.PHONY: all
all:
	make numpy-1.16.1-cp36-cp36m-linux_aarch64.whl
	make scikit_image-0.14.2-cp36-cp36m-linux_aarch64.whl
	make h5py-2.10.0-cp36-cp36m-linux_aarch64.whl

numpy-1.16.1-cp36-cp36m-linux_aarch64.whl:
	pip3 wheel numpy==1.16.1
scikit_image-0.14.2-cp36-cp36m-linux_aarch64.whl:
	pip3 wheel scikit-image==0.14.2
h5py-2.10.0-cp36-cp36m-linux_aarch64.whl:
	pip3 wheel h5py==2.10.0
#add grpcio too
