tator:
  host: "https://www.tatorapp.com"
  token: "TATOR_TOKEN"
collect_data: True
plot_file_starts: False
data_config:
  project_id: 31
  state_type: 159 # The inferred state type
  gt_state_type: 149 # The annotated state type
  gt_versions: [51] # The version in which the annotated states live
  media_type: 55 # The multivideo type id
  versions: # The versions in which the inferred states live; keys are version names
    AF: [211]
    NA: [210]
    LM: [212]
  trips: # The list of section names to plot
  - "AF-20190806_Trip"
  - "AF-20190815_Trip"
  - "LM-20200824_Trip"
  - "LM-20200825_Trip"
  - "NA-20191007_Trip"
  - "NA-20191008_Trip"
  activities: # The choices from the activities to visualize
  - "Background"
  - "Offloading"
  - "Net Activity"
  - "Fish Presence"
  destination_folder: "plot_states_out" # Where to store the data and plots
  data_filename: "data.pkl" # Intermediate data file
